name: satisfied_version
description: Check whether the version is satisfied with provided String, List, or Map of versions or not.
version: 0.1.0+2
homepage: https://github.com/vnniz/satisfied_version

environment:
  sdk: ">=2.17.0 <3.0.0"

dev_dependencies:
  test: ^1.21.3
  lints: ^2.0.0
