name: satisfied_version
description: Check whether the version is satisfied with provided String, List, or Map of versions or not.
version: 0.3.0
homepage: https://github.com/vnniz/satisfied_version

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  test: ^1.24.6
  lints: ^2.1.1
