name: satisfied_version
description: Compare and check whether the version is satisfied with provided version (or build number) in String, List, or Map.
version: 0.4.2
homepage: https://github.com/lamnhan066/satisfied_version

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  test: ^1.24.6
  lints: ^5.1.1
